// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type History struct {
	ID          pgtype.UUID      `json:"id"`
	EntityID    pgtype.UUID      `json:"entity_id"`
	EntityTable string           `json:"entity_table"`
	Type        string           `json:"type"`
	Key         string           `json:"key"`
	Value       string           `json:"value"`
	Meta        []byte           `json:"meta"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
}

type Message struct {
	ID        pgtype.UUID      `json:"id"`
	Content   *string          `json:"content"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
	DeletedAt pgtype.Timestamp `json:"deleted_at"`
	NoScript  bool             `json:"no_script"`
}

type MessageButton struct {
	ID        pgtype.UUID      `json:"id"`
	MessageID pgtype.UUID      `json:"message_id"`
	Text      string           `json:"text"`
	Url       *string          `json:"url"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
	DeletedAt pgtype.Timestamp `json:"deleted_at"`
}

type MessageMedium struct {
	ID         pgtype.UUID      `json:"id"`
	UploadedBy pgtype.UUID      `json:"uploaded_by"`
	MessageID  pgtype.UUID      `json:"message_id"`
	StorageKey string           `json:"storage_key"`
	Ext        string           `json:"ext"`
	Size       int64            `json:"size"`
	MimeType   string           `json:"mime_type"`
	CreatedAt  pgtype.Timestamp `json:"created_at"`
	DeletedAt  pgtype.Timestamp `json:"deleted_at"`
}

type ScheduledStep struct {
	ID               pgtype.UUID      `json:"id"`
	ScriptProgressID pgtype.UUID      `json:"script_progress_id"`
	ExecuteAt        pgtype.Timestamp `json:"execute_at"`
	Status           string           `json:"status"`
	SendAt           pgtype.Timestamp `json:"send_at"`
	SentAt           pgtype.Timestamp `json:"sent_at"`
	Attempts         int32            `json:"attempts"`
	LastError        *string          `json:"last_error"`
	CreatedAt        pgtype.Timestamp `json:"created_at"`
}

type Script struct {
	ID             pgtype.UUID      `json:"id"`
	Name           string           `json:"name"`
	IsActive       bool             `json:"is_active"`
	PrivateGroupID pgtype.UUID      `json:"private_group_id"`
	CreatedAt      pgtype.Timestamp `json:"created_at"`
	UpdatedAt      pgtype.Timestamp `json:"updated_at"`
	DeletedAt      pgtype.Timestamp `json:"deleted_at"`
}

type ScriptProgress struct {
	ID            pgtype.UUID      `json:"id"`
	UserID        pgtype.UUID      `json:"user_id"`
	ScriptID      pgtype.UUID      `json:"script_id"`
	CurrentStepID pgtype.UUID      `json:"current_step_id"`
	Status        string           `json:"status"`
	StepStartedAt pgtype.Timestamp `json:"step_started_at"`
	StartedAt     pgtype.Timestamp `json:"started_at"`
	FinishedAt    pgtype.Timestamp `json:"finished_at"`
}

type ScriptProgressDelivery struct {
	ID                pgtype.UUID      `json:"id"`
	MessageID         pgtype.UUID      `json:"message_id"`
	StepID            pgtype.UUID      `json:"step_id"`
	ScriptProgressID  pgtype.UUID      `json:"script_progress_id"`
	SentAt            pgtype.Timestamp `json:"sent_at"`
	Channel           string           `json:"channel"`
	Snapshot          []byte           `json:"snapshot"`
	TelegramMessageID string           `json:"telegram_message_id"`
}

type ScriptStep struct {
	ID          pgtype.UUID      `json:"id"`
	ScriptID    pgtype.UUID      `json:"script_id"`
	MessageID   pgtype.UUID      `json:"message_id"`
	Order       int32            `json:"order"`
	Channel     string           `json:"channel"`
	Timing      *int32           `json:"timing"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	UpdatedAt   pgtype.Timestamp `json:"updated_at"`
	DeletedAt   pgtype.Timestamp `json:"deleted_at"`
	SkipOnError bool             `json:"skip_on_error"`
}

type TelegramBot struct {
	ID             pgtype.UUID      `json:"id"`
	OwnerID        pgtype.UUID      `json:"owner_id"`
	BotID          *int64           `json:"bot_id"`
	Username       string           `json:"username"`
	FirstName      *string          `json:"first_name"`
	EncryptedToken string           `json:"encrypted_token"`
	Status         string           `json:"status"`
	LastError      *string          `json:"last_error"`
	LastCheckedAt  pgtype.Timestamp `json:"last_checked_at"`
	RevokedAt      pgtype.Timestamp `json:"revoked_at"`
	CreatedAt      pgtype.Timestamp `json:"created_at"`
	UpdatedAt      pgtype.Timestamp `json:"updated_at"`
}

type User struct {
	ID         pgtype.UUID      `json:"id"`
	TelegramID *int64           `json:"telegram_id"`
	Username   *string          `json:"username"`
	FirstName  *string          `json:"first_name"`
	LastName   *string          `json:"last_name"`
	Role       string           `json:"role"`
	CreatedAt  pgtype.Timestamp `json:"created_at"`
	IsActive   bool             `json:"is_active"`
	BlockedAt  pgtype.Timestamp `json:"blocked_at"`
}
